default-group: default
# The name of the group that is assigned to all players with no other groups assigned by a permission node. It should be defined in the groups section.

update-cycle: 10
# The number of seconds between two rule checks (used for other stuff too).

# GROUPS
#
# Groups are used to apply certain behaviors to specific players.
# Groups have rule sets, whereby rules in these rule sets basically make changes to the data of the players in the group at certain times.
# Groups are assigned by a permission 'limiter.group.{groupname}' whereby {groupname} refers to a key in this groups section.
groups:
  default:
    start-timer: 1000000
    start-mode: ticking
    rules:
      daily:
        when:
          time: '0:00'
        action:
          changetimer: '5:00'
      night:
        when:
          time: '21:00'
        action:
          restrict: deny
      morning:
        when:
          time: '7:00'
        action:
          restrict: allow
    on-expiration:
      command: tellraw "Time's up!"