name: PlaytimeLimiter
version: '1.0-SNAPSHOT'
main: io.annhilati.playtimelimiter.PlaytimeLimiter
api-version: '1.21'
authors: [ Annhilati ]
commands:
  limiter:
permissions:
  limiter.admin:
    default: op
softdepend: [
  PlaceholderAPI
]
